#!/usr/bin/env python

import dht.kademlia
import logging
import argparse
from twisted.application import service

def main():
    parser = argparse.ArgumentParser(description="Nightmare PUB/SUB")
    parser.add_argument("--logfile", default="nightmare.log", 
                    help="The name of the log file (default: nightmare.log)")
    args = parser.parse_args()
    logging.basicConfig(filename=args.logfile,level=logging.DEBUG)
    logging.info("Staring Kademlia")
    node = dht.kademlia.Kademlia()
    

if __name__ == "__main__":
    main()
