#!/usr/bin/env python

import logging
import argparse
from twisted.application import service, internet
from dht.kademliaproto import KademliaService, IPerspectiveKademlia
from dht.kademlia import Kademlia
from twisted.spread import pb

def main():
    parser = argparse.ArgumentParser(description="Nightmare PUB/SUB")
    parser.add_argument("--logfile", default="nightmare.log", 
                    help="The name of the log file (default: nightmare.log)")
    args = parser.parse_args()
    logging.basicConfig(filename=args.logfile,level=logging.DEBUG)
    logging.info("Staring Kademlia")
    application = service.Application('nightmare', uid=1, gid=1)
    kademlia = Kademlia()
    kademliaService = KademliaService(kademlia)
    serviceCollection = service.IServiceCollection(application)
    kademliaService.setServiceParent(serviceCollection)
    internet.TCPServer(56789, pb.PBServerFactory(IPerspectiveKademlia(kademliaService))).setServiceParent(serviceCollection)

if __name__ == "__main__":
    main()
